const config = {
  MONGODB_URI: process.env.MONGODB_URI,
  PORT: process.env.PORT || 3000,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || "",
  THIRDWEB_SECRET_KEY: process.env.THIRDWEB_SECRET_KEY,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || "",
  GEMINI_MODEL: process.env.GEMINI_MODEL || "gemini-2.5-flash",
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID: process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID,
  SERVER_WALLET_ADDRESS: process.env.SERVER_WALLET_ADDRESS || "",
  APP_URL: getAppUrl(),
  NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS || "",
  NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS: process.env
    .NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS
    ? parseInt(process.env.NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS)
    : 6,
  NEXT_PUBLIC_PAYMENT_TOKEN_SYMBOL:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_SYMBOL || "",
  CRYPTO_COM_API_KEY: process.env.CRYPTO_COM_API_KEY || "",
  NEXT_PUBLIC_CRONOS_EXPLORER_URL:
    process.env.NEXT_PUBLIC_CRONOS_EXPLORER_URL || "",
  NEXT_PUBLIC_AGENT_FACTORY_ADDRESS:
    process.env.NEXT_PUBLIC_AGENT_FACTORY_ADDRESS || "",
  NEXT_PUBLIC_AGENT_FACTORY_DEPLOYMENT_FEE_CRO: process.env
    .NEXT_PUBLIC_AGENT_FACTORY_DEPLOYMENT_FEE_CRO
    ? parseFloat(process.env.NEXT_PUBLIC_AGENT_FACTORY_DEPLOYMENT_FEE_CRO)
    : 0,
  NEXT_PUBLIC_AGENT_FACTORY_DEPLOYMENT_FEE_WEI: process.env
    .NEXT_PUBLIC_AGENT_FACTORY_DEPLOYMENT_FEE_WEI
    ? process.env.NEXT_PUBLIC_AGENT_FACTORY_DEPLOYMENT_FEE_WEI
    : "0",
  NEXT_PUBLIC_AGENT_FACTORY_OWNER:
    process.env.NEXT_PUBLIC_AGENT_FACTORY_OWNER || "",
  CONTEXT: process.env.CONTEXT || "",
};

function getAppUrl() {
  if (process.env.NODE_ENV === "production") {
    return "https://xmind-dusky.vercel.app/";
  } else {
    return `http://localhost:3000/`;
  }
}

export default config;
