# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
  experimental-chains:
    - chain-selector: 14767482510784806043
      rpc-url: https://api.avax-test.network/ext/bc/C/rpc
      forwarder: "0x0000000000000000000000000000000000000000"

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
  experimental-chains:
    - chain-selector: 14767482510784806043
      rpc-url: https://api.avax-test.network/ext/bc/C/rpc
      forwarder: "0x0000000000000000000000000000000000000000"
