import dbConnect from "@/lib/db/mongodb";
import { VaultAgent } from "@/lib/models/VaultAgent";
import { AgentAction } from "@/lib/models/AgentAction";
import { NextRequest, NextResponse } from "next/server";

/**
 * GET /api/cre/history?vaultAddress=0x...
 *
 * Fetches the execution history logs generated by the Chainlink CRE Orchestrator
 * for a specific Vault Agent.
 */
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const vaultAddress = searchParams.get("vaultAddress");

  if (!vaultAddress) {
    return NextResponse.json({ error: "Missing vaultAddress" }, { status: 400 });
  }

  try {
    await dbConnect();

    const agent = await VaultAgent.findOne({ vaultAddress: vaultAddress.toLowerCase() });
    if (!agent) {
      return NextResponse.json({ error: "Agent not found" }, { status: 404 });
    }

    const actions = await AgentAction.find({ agentId: agent._id })
      .sort({ createdAt: -1 })
      .limit(50) // Only fetch the 50 most recent actions
      .lean();

    return NextResponse.json({ success: true, actions });
  } catch (error) {
    console.error("[CRE] history GET error:", error);
    return NextResponse.json(
      { error: "Failed to fetch history" },
      { status: 500 }
    );
  }
}
